configfile: "config.yaml"

shell.executable("bash")

import os


PROJECT_DIR = config.get("working_dir", workflow.basedir)
CONFIG_PATH = config.get("config_path", os.path.join(PROJECT_DIR, "config.yaml"))
R_VERSION = str(config["r_version"])

# Keep this ordering aligned with the FIPS CSV generated by the download step.
CONUS_STATE_FIPS = [
    "01", "04", "05", "06", "08", "09", "10", "11", "12", "13",
    "16", "17", "18", "19", "20", "21", "22", "23", "24", "25",
    "26", "27", "28", "29", "30", "31", "32", "33", "34", "35",
    "36", "37", "38", "39", "40", "41", "42", "44", "45", "46",
    "47", "48", "49", "50", "51", "53", "54", "55", "56",
]

VALID_DECYEARS = [2000, 2010, 2020]


def normalize_state_fips(raw_state_fips):
    if isinstance(raw_state_fips, str):
        if raw_state_fips.lower() == "nationwide":
            return CONUS_STATE_FIPS
        return [raw_state_fips.zfill(2)]

    supplied = {str(state).zfill(2) for state in raw_state_fips}
    return [state for state in CONUS_STATE_FIPS if state in supplied]


def map_decyear_by_year(year, decyear_config):
    year = int(year)
    decyear_config = [int(decyear) for decyear in decyear_config if decyear is not None]

    if len(decyear_config) == 1 and decyear_config[0] in VALID_DECYEARS:
        return decyear_config[0]

    auto_map = len(decyear_config) == 0 or any(
        decyear not in VALID_DECYEARS for decyear in decyear_config
    )
    if auto_map:
        if year < 2010:
            return 2000
        if year < 2020:
            return 2010
        return 2020

    if year < 2010 and 2000 in decyear_config:
        return 2000
    if 2010 <= year < 2020 and 2010 in decyear_config:
        return 2010
    if year >= 2020 and 2020 in decyear_config:
        return 2020

    decyear_config = sorted(set(decyear_config))
    prior = [decyear for decyear in decyear_config if decyear <= year]
    if prior:
        return max(prior)
    return min(decyear_config)


def abr(decyear):
    return str(decyear)[2:4]


def cfg_path(path_key, *parts):
    path = config["paths"][path_key]
    return os.path.join(path, *parts)


def check_year_decyear(year, decyear_abr):
    decyear = DECYEAR_BY_YEAR[int(year)]
    expected = abr(decyear)
    if decyear_abr != expected:
        raise ValueError(
            f"Year {year} maps to decennial suffix {expected}, not {decyear_abr}."
        )
    return decyear


STATE_FIPS = normalize_state_fips(config["processing"]["state_fips"])
STATE_INDEX = {state: index + 1 for index, state in enumerate(STATE_FIPS)}
YEARS = [int(year) for year in config["processing"]["years_to_process"]]
EXP_LIST = [str(var) for var in config["processing"]["exp_list"]]
PRISM_VAR_PATTERN = "|".join(EXP_LIST)
CONFIG_DECYEARS = [int(year) for year in config["processing"]["decyear"]]
DECYEAR_BY_YEAR = {year: map_decyear_by_year(year, CONFIG_DECYEARS) for year in YEARS}
USED_DECYEARS = sorted(set(DECYEAR_BY_YEAR.values()))
USED_DECYEAR_ABRS = [abr(decyear) for decyear in USED_DECYEARS]

FISHNET_YEAR = int(config["fishnet"]["year"])
FISHNET_VAR = str(config["fishnet"]["variable"])

FIPS_CSV = cfg_path("fips_csv")
FISHNET_OUTPUT = cfg_path("fishnet_dir", f"prism_fishnet_{FISHNET_VAR}_800m.gpkg")


def state_index(wildcards):
    return STATE_INDEX[wildcards.state]


def decyear_from_abr(decyear_abr):
    matches = [decyear for decyear in USED_DECYEARS if abr(decyear) == decyear_abr]
    if not matches:
        raise ValueError(f"Unsupported decennial suffix: {decyear_abr}")
    return matches[0]


def extraction_points_file(decyear, state):
    return cfg_path(
        "extraction_pts_dir",
        f"PRISM_extraction_points_tl{abr(decyear)}_block_{state}.rds",
    )


def prism_year_dir(var, year):
    return cfg_path("rawdata_dir", str(var), str(year))


def prism_year_manifest(var, year):
    return os.path.join(prism_year_dir(var, year), ".download_complete")


def block_shapefile_stem(decyear, state):
    decyear = str(decyear)
    tiger_year = "2020" if decyear == "2020" else "2010"
    suffix = decyear[2:4]
    return cfg_path(
        "block_shapefile_dir",
        decyear,
        f"tl_{tiger_year}_{state}_tabblock{suffix}",
    )


def block_shapefile_components(decyear, state):
    stem = block_shapefile_stem(decyear, state)
    return [stem + ext for ext in [".shp", ".shx", ".dbf", ".prj"]]


def block_file(year, state):
    decyear = DECYEAR_BY_YEAR[int(year)]
    decyear_abr = abr(decyear)
    return cfg_path(
        "block_outdir",
        f"blocks_{decyear_abr}",
        str(year),
        f"tl{decyear_abr}_prism_daily_{year}_{state}.rds",
    )


def zcta_state_file(year, state):
    decyear = DECYEAR_BY_YEAR[int(year)]
    decyear_abr = abr(decyear)
    return cfg_path(
        "zcta_outdir",
        f"zcta_{decyear_abr}",
        f"PRISM_ZCTA{decyear_abr}_{year}_{state}.Rds",
    )


def crosswalk_zcta_gpkg(decyear):
    return cfg_path("crosswalk_dir", "zcta", f"ZCTA_{decyear}_US.gpkg")


def crosswalk_zcta_population(decyear):
    return cfg_path("crosswalk_dir", "population", f"zcta_population_{decyear}_US.Rds")


def crosswalk_block_population(decyear, state):
    return cfg_path(
        "crosswalk_dir",
        "population",
        f"block_population_{decyear}_{state}.Rds",
    )


def block_to_zcta_file(decyear, state):
    return cfg_path("crosswalk_dir", f"Block_to_ZCTA_{decyear}_{state}.Rds")


def zcta_state_weight_file(decyear):
    return cfg_path("crosswalk_dir", f"ZCTA_StateWt_{decyear}_US.Rds")


def national_block_to_zcta_file(decyear):
    return cfg_path("crosswalk_dir", f"Block_to_ZCTA_{decyear}_US.Rds")


def zcta_nation_file(year):
    decyear = DECYEAR_BY_YEAR[int(year)]
    decyear_abr = abr(decyear)
    return cfg_path(
        "nation_dir",
        f"PRISM_ZCTA{decyear_abr}_{year}_nation.rds",
    )


def daily_parquet(year):
    return os.path.join(
        "outputdata",
        "meteorology__prism",
        "population_weighted",
        "zcta_daily",
        f"meteorology__gridmet__zcta_daily__{year}.parquet",
    )


def yearly_parquet(year):
    return os.path.join(
        "outputdata",
        "meteorology__prism",
        "population_weighted",
        "zcta_yearly",
        f"meteorology__gridmet__zcta_yearly__{year}.parquet",
    )


EXTRACTION_POINT_OUTPUTS = [
    extraction_points_file(decyear, state)
    for decyear in USED_DECYEARS
    for state in STATE_FIPS
]
BLOCK_OUTPUTS = [block_file(year, state) for year in YEARS for state in STATE_FIPS]
PRISM_YEAR_DIRS = [
    prism_year_dir(var, year)
    for var in EXP_LIST
    for year in YEARS
]
PRISM_YEAR_MANIFESTS = [
    prism_year_manifest(var, year)
    for var in EXP_LIST
    for year in YEARS
]
BLOCK_SHAPEFILE_OUTPUTS = [
    block_shapefile_components(decyear, state)
    for decyear in USED_DECYEARS
    for state in STATE_FIPS
]
BLOCK_TO_ZCTA_OUTPUTS = [
    block_to_zcta_file(decyear, state)
    for decyear in USED_DECYEARS
    for state in STATE_FIPS
]
ZCTA_STATE_WEIGHT_OUTPUTS = [
    zcta_state_weight_file(decyear)
    for decyear in USED_DECYEARS
]
NATIONAL_BLOCK_TO_ZCTA_OUTPUTS = [
    national_block_to_zcta_file(decyear)
    for decyear in USED_DECYEARS
]
ZCTA_STATE_OUTPUTS = [zcta_state_file(year, state) for year in YEARS for state in STATE_FIPS]
ZCTA_NATION_OUTPUTS = [zcta_nation_file(year) for year in YEARS]
DAILY_PARQUETS = [daily_parquet(year) for year in YEARS]
YEARLY_PARQUETS = [yearly_parquet(year) for year in YEARS]


rule all:
    input:
        ZCTA_NATION_OUTPUTS,
        DAILY_PARQUETS,
        YEARLY_PARQUETS


rule download_fips_csv:
    input:
        config=CONFIG_PATH,
    output:
        FIPS_CSV,
    params:
        outdir=os.path.dirname(FIPS_CSV),
        r_version=R_VERSION,
    threads: 1
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/X_Build_FIPS_CSV_v01.R {input.config}
        """


rule download_prism_year:
    wildcard_constraints:
        var=PRISM_VAR_PATTERN,
        year=r"\d{4}"
    input:
        config=CONFIG_PATH,
    output:
        prism_year_manifest("{var}", "{year}"),
    params:
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        r_version=R_VERSION,
    threads: 1
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/X_Download_PRISM800m_VarYear_v01.R {wildcards.var} {wildcards.year} {input.config}
        """


rule download_block_shapefile:
    input:
        config=CONFIG_PATH,
    output:
        block_shapefile_components("{decyear}", "{state}"),
    params:
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
    threads: 1
    shell:
        """
        set -euo pipefail
        bash code/X_Download_Census_Block_Shapefile_v01.sh {wildcards.decyear} {wildcards.state} {params.outdir}
        """


rule fishnet:
    input:
        config=CONFIG_PATH,
        prism_ref=prism_year_manifest(FISHNET_VAR, FISHNET_YEAR),
    output:
        FISHNET_OUTPUT,
    params:
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        r_version=R_VERSION,
    threads: 16
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/00a_Create_Fishnet_PRISMv2_800m_v03.R {input.config}
        """


rule extraction_points:
    input:
        config=CONFIG_PATH,
        fips=FIPS_CSV,
        fishnet=FISHNET_OUTPUT,
        prism_ref=prism_year_manifest(FISHNET_VAR, FISHNET_YEAR),
        block_shp=lambda wildcards: block_shapefile_components(
            decyear_from_abr(wildcards.decyear_abr),
            wildcards.state,
        ),
    output:
        cfg_path(
            "extraction_pts_dir",
            "PRISM_extraction_points_tl{decyear_abr}_block_{state}.rds",
        ),
    params:
        decyear=lambda wildcards: decyear_from_abr(wildcards.decyear_abr),
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        state_idx=state_index,
        r_version=R_VERSION,
    threads: 4
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/01a_Extraction_Pts_v03.R {params.state_idx} {params.decyear} {input.config}
        """


rule raster_extract:
    input:
        config=CONFIG_PATH,
        prism_manifests=lambda wildcards: [
            prism_year_manifest(var, wildcards.year)
            for var in EXP_LIST
        ],
        extraction_points=lambda wildcards: extraction_points_file(
            DECYEAR_BY_YEAR[int(wildcards.year)],
            wildcards.state,
        ),
    output:
        cfg_path(
            "block_outdir",
            "blocks_{decyear_abr}",
            "{year}",
            "tl{decyear_abr}_prism_daily_{year}_{state}.rds",
        ),
    params:
        decyear=lambda wildcards: check_year_decyear(
            wildcards.year,
            wildcards.decyear_abr,
        ),
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        state_idx=state_index,
        r_version=R_VERSION,
    threads: 16
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/02a_PRISM_Raster_Extract_v03.R {wildcards.year} {params.state_idx} {input.config}
        """


rule crosswalk_zcta_inputs:
    input:
        config=CONFIG_PATH,
    output:
        zcta=crosswalk_zcta_gpkg("{decyear}"),
        zcta_pop=crosswalk_zcta_population("{decyear}"),
    params:
        zcta_dir=lambda wildcards, output: os.path.dirname(output.zcta),
        pop_dir=lambda wildcards, output: os.path.dirname(output.zcta_pop),
        r_version=R_VERSION,
    threads: 4
    shell:
        """
        set -euo pipefail
        mkdir -p {params.zcta_dir} {params.pop_dir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/06a_Crosswalk_ZCTA_Inputs_v01.R {wildcards.decyear} {input.config}
        """


rule crosswalk_block_population:
    input:
        config=CONFIG_PATH,
    output:
        crosswalk_block_population("{decyear}", "{state}"),
    params:
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        state_idx=state_index,
        r_version=R_VERSION,
    threads: 2
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/06b_Crosswalk_Block_Population_v01.R {params.state_idx} {wildcards.decyear} {input.config}
        """


rule block_to_zcta_crosswalk:
    input:
        config=CONFIG_PATH,
        zcta=lambda wildcards: crosswalk_zcta_gpkg(wildcards.decyear),
        block_pop=lambda wildcards: crosswalk_block_population(
            wildcards.decyear,
            wildcards.state,
        ),
        block_shp=lambda wildcards: block_shapefile_components(
            wildcards.decyear,
            wildcards.state,
        ),
    output:
        block_to_zcta_file("{decyear}", "{state}"),
    params:
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        state_idx=state_index,
        r_version=R_VERSION,
    threads: 8
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/06c_Build_Block_to_ZCTA_Crosswalk_v01.R {params.state_idx} {wildcards.decyear} {input.config}
        """


rule zcta_state_weights:
    input:
        config=CONFIG_PATH,
        state_crosswalks=lambda wildcards: [
            block_to_zcta_file(wildcards.decyear, state)
            for state in STATE_FIPS
        ],
        zcta_pop=lambda wildcards: crosswalk_zcta_population(wildcards.decyear),
    output:
        weights=zcta_state_weight_file("{decyear}"),
        national=national_block_to_zcta_file("{decyear}"),
    params:
        outdir=lambda wildcards, output: os.path.dirname(output.weights),
        r_version=R_VERSION,
    threads: 4
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/06d_Merge_Block_to_ZCTA_Crosswalk_v01.R {wildcards.decyear} {input.config}
        """


rule zcta_state:
    input:
        config=CONFIG_PATH,
        blocks=lambda wildcards: block_file(wildcards.year, wildcards.state),
        crosswalk=lambda wildcards: block_to_zcta_file(
            DECYEAR_BY_YEAR[int(wildcards.year)],
            wildcards.state,
        ),
    output:
        cfg_path(
            "zcta_outdir",
            "zcta_{decyear_abr}",
            "PRISM_ZCTA{decyear_abr}_{year}_{state}.Rds",
        ),
    params:
        decyear=lambda wildcards: check_year_decyear(
            wildcards.year,
            wildcards.decyear_abr,
        ),
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        state_idx=state_index,
        r_version=R_VERSION,
    threads: 28
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/03a_BlockPop_Wt_ZCTA_PRISM_800m_v03.R {wildcards.year} {params.state_idx} {input.config}
        """


rule zcta_nationwide:
    input:
        config=CONFIG_PATH,
        state_files=ZCTA_STATE_OUTPUTS,
        weights=ZCTA_STATE_WEIGHT_OUTPUTS,
    output:
        ZCTA_NATION_OUTPUTS,
    params:
        outdir=lambda wildcards, output: os.path.dirname(output[0]),
        r_version=R_VERSION,
    threads: 16
    shell:
        """
        set -euo pipefail
        mkdir -p {params.outdir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/04_Zip2Zcta_Cleaning_PRISM_allyrs_v01.R {input.config}
        """


rule reshape_zcta_outputs:
    input:
        config=CONFIG_PATH,
        nationwide=ZCTA_NATION_OUTPUTS,
    output:
        daily=DAILY_PARQUETS,
        yearly=YEARLY_PARQUETS,
    params:
        daily_dir=lambda wildcards, output: os.path.dirname(output.daily[0]),
        yearly_dir=lambda wildcards, output: os.path.dirname(output.yearly[0]),
        r_version=R_VERSION,
    threads: 4
    shell:
        """
        set -euo pipefail
        mkdir -p {params.daily_dir} {params.yearly_dir}
        export R_VERSION={params.r_version}
        source code/slurm_runtime_env.sh
        Rscript code/05_Reshape_PRISM_ZCTA_Output_v01.R {input.config}
        """
